### ISSUE TITLE
[Bug] StoreListener's can't trigger but can update just fine.

### ISSUE THREAD

**Issue by darkyen** [deloreanjs/delorean#66] opened 2015-01-25 13:22 UTC
In my view 
```

import React from 'react';
import Header from './../header';
import {List} from './../listview';
import {Flux} from 'delorean';

var OverlaySearchView = React.createClass({

  mixins: [Flux.mixins.storeListener],
  watchStores: ['searchStore'],

  handleFocus(){
    console.log("focus");
    this.setState({
      searchViewActive: true
    });
  },

  handleBlur(){
    console.log("blur");
    this.setState({
      searchViewActive: false
    });
  },

  addToCart(e, element){
    cartActions.addToCart(element);
  },

  updateSearch(e){
    var query = e.target.value;
    if( query.length > 2 ){
      // Never triggers
      return this.trigger('search:query:' + this.props.searchType, query);
    }
    // Neither does this
    this.trigger('search:clear');
  },

  render(){
    var searchResults = '';
    console.log('Current results', this.getStore('searchStore'), this.__dispatcher);
    // Logs the current results and the dispatcher 

    var isActive = this.state.searchViewActive;

    if( true && isActive === true ){
      var medicines = this.getStore('searchStore');
      searchResults = (
        <div onClick={this.handleBlur}>
          <div className="search-view-overlay">
          </div>
          <div className="search-results">
            <List onClick={this.addToCart} elementRenderer={this.props.searchElementRenderer} source={medicines}></List>
          </div>
        </div>
      );
    }
    return (
      <div className={ "search-view" + (isActive?' active': '')}>
        <Header>
          <input className="search-bar form-control no-borders"  placeholder="Search" type="text"
            onFocus={this.handleFocus} onChange={this.updateSearch} />
        </Header>
        {searchResults}
      </div>
    );
  }
});


export default OverlaySearchView;
```
The above component is nested inside a Router.State + Delorean.Flux.mixins.storeListener view from React-Router and delorean

Am i doing something wrong here  ?

**Comment by darcyadams** [comment] 2015-01-25 17:40
are you sure the dispatcher has been passed as a `prop` somewhere in the component chain?

**Comment by darkyen** [comment] 2015-01-25 19:25
@darcyadams this.trigger is defined and

```
  function __findDispatcher(view) {
     // Provide a useful error message if no dispatcher is found in the chain
    if (view == null) {
      throw 'No disaptcher found. The DeLoreanJS mixin requires a "dispatcher" property to be passed to a component, or one of it\'s ancestors.';
    }
    /* `view` should be a component instance. If a component don't have
        any dispatcher, it tries to find a dispatcher from the parents. */
    if (!view.props.dispatcher) {
      return __findDispatcher(view._owner);
    }
    return view.props.dispatcher;
  }

```

Should be able to get the dispatcher from the top root, which it does (which is why __dispatcher is defined)

**Comment by darcyadams** [comment] 2015-01-25 19:29
what about your dispatcher code? can you share that? it seems like the trigger is firing, but it there is just nothing handling the specific 'event'.

**Comment by darcyadams** [comment] 2015-01-26 14:02
I'm gonna close this issue, for now. As there doesn't seem to be any evidence of a bug, but please let me know if you need further help. Always happy to assist.

FYI, I use the `viewTriggers` feature in a large React application everyday. So I'm fairly certain they are working as intended. Just remember that the handlers live in the `dispatcher` not the stores (they are different than store `actions`).

**Closed by darcyadams** 2015-01-26 14:02 UTC

**Comment by darkyen** [comment] 2015-01-26 19:12
@darcyadams Me too, this is the first time i faced it. Probably something wrong I did for now I am on the move and hence didn't got a chance to update you on it, I restructured my application and made seperate components for React.Router and storeListener it works fine for now. I will try to update you as soon as I can
